### ISSUE TITLE
test函数问题

### ISSUE THREAD

**Issue by ChineseDragon-code** [hanc00l/wifitest#4]
test setup failed
file D:\PyCharm 6.28\wifitest\wifitest.py, line 69
  def test(i,face,x,key,stu,ts):
E       fixture 'i' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, doctest_namespace, event_loop, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory, unused_tcp_port, unused_tcp_port_factory
>       use 'pytest --fixtures [testpath]' for help on them.

D:\PyCharm 6.28\wifitest\wifitest.py:69

**Comment by hanc00l** [comment]
感谢。google了一下，是不是这个原因：[fixture 'xxx' not found](https://blog.csdn.net/weixin_44017891/article/details/103418031?utm_medium=distribute.pc_relevant.none-task-blog-BlogCommendFromMachineLearnPai2-1.control&depth_1-utm_source=distribute.pc_relevant.none-task-blog-BlogCommendFromMachineLearnPai2-1.control)

>由于pycharm中以pytest运行，它会默认把test、test_开头的.py文件当做单元测试，所以需要修改文件名。他将test_interview.py 修改为interview.py ，再次运行，成功了。
>
>所以，我这里用到了test函数名，应该也是有问题的（具体原因是为什么，我现在也还不清楚）。
